# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_analysis
    test_fault_wrappers_compile_command
    test_fault_wrappers_facts
    test_fault_wrappers_project
)
